version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    container_name: simbox-container
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true